jwt:
  secret:
    key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  access:
    token:
      expiration: 60000
  refresh: 
    token:
      expiration: 3600000

spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:configserver:http://localhost:8766
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/naming-server/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env


  