services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tutorial-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - tutorial-network
      
  config-server:
    image: debapriyapal/config-server:0.0.1
    mem_limit: 200m
    container_name: config-server
    ports:
      - "8766:8766"
    networks:
      - tutorial-network

  naming-server:
    image: debapriyapal/naming-server:0.0.1
    mem_limit: 700m
    container_name: naming-server
    ports:
      - "8761:8761"
    networks:
      - tutorial-network
      
  api-gateway:
    image: debapriyapal/api-gateway:0.0.1
    container_name: api-gateway
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - tutorial-network
    depends_on:
      config-server:
        condition: service_started
      naming-server:
        condition: service_started
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      
  #currency-exchange-service:
  #  image: debapriyapal/currency-exchange-service:0.0.1-SNAPSHOT
  #  mem_limit: 700m
  #  ports:
  #    - "8001:8001"
  #  networks:
  #    - currency-network
  #  depends_on:
  #    - naming-server
  #  environment:
  #    EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
  #    MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      
  #currency-conversion-service:
  #  image: debapriyapal/currency-conversion-service:0.0.1-SNAPSHOT
  #  mem_limit: 700m
  #  ports:
  #    - "8101:8101"
  #  networks:
  #    - currency-network
  #  depends_on:
  #    - naming-server
  #  environment:
  #    EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
  #    MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
  
  user-service:
    image: debapriyapal/user-service:0.0.1
    container_name: user-service
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - tutorial-network
    depends_on:
      config-server:
        condition: service_started
      naming-server:
        condition: service_started
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      spring.data.redis.host: redis
      spring.data.redis.port: 6379
      
  aaa-service:
    image: debapriyapal/aaa-service:0.0.1
    container_name: aaa-service
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - tutorial-network
    depends_on:
      config-server:
        condition: service_started
      naming-server:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/naming-server/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      spring.data.redis.host: redis
      spring.data.redis.port: 6379

  zipkin-server:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - tutorial-network
    restart: always #Restart if there is a problem starting up
      
networks:
  tutorial-network: